#!/bin/sh

# BUTTON MAPPING FOR EVOLUENT MOUSE
xinput set-button-map "Kingsis Peripherals Evoluent VerticalMouse 4" 1 3 2 4 5 6 7 8 2 2
#btn1, btn2, btn3, scrollup, scrolldown, nothing, nothing, thumbtop, middleclick, thumbdown

# REVERSE SCROLL DIRECTINO
pointer = 1 2 3 5 4 6 7 8 9 10 11 12

# KEYBOARD REPEAT
xset r rate 250 25
