#!/bin/sh

############
### MICE ###
############

# Evoluent
# --- M-Click on scroll-wheel & bottom thumb. Nothing on 3rd button

#  1 l-click
#  2 r-click
#  3 m-click
#  4 scroll-up
#  5 scroll-dn
#  6 ?
#  7 ?
#  8 thumb-t       (enter)
#  9 scroll-click  (m-click)
# 10 thumb-b       (m-click)

xinput set-button-map "Kingsis Peripherals Evoluent VerticalMouse 4" 1 3 0 4 5 6 7 8 2 2


# Elecom Huge
# --- R and M click on right side. and L and R click above scroll wheel. No small Fn

#  1 L
#  2 scroll-click-m  (m-click)
#  3 R               (m-click)
#  4 scroll-up
#  5 scroll-dn
#  6 scroll-click-d  (m-click)
#  7 scroll-click-u  (?)
#  8 rarr            (r-click)
#  9 larr            (l-click)
# 10 Fn1             (?)
# 11 Fn2             (?)
# 12 Fn3             (r-click)

xinput set-button-map 14  1 2 2 4 5 2 7 3 1 10 11 3

# Mionix NAOS
# --- Map front thumb to M-click. Back thumb not able to remap??

#  1 l-click
#  2 scroll-click
#  3 r-click
#  4 scroll-up
#  5 scroll-dn
#  6 ?
#  7 ?
#  8 thumb-fr      (m-click)
#  9 thumb-bk
# 10 ?
# 11 ?
# 12 ?
# xinput set-button-map "La-VIEW Technology Mionix NAOS 7000" 1 2 3 4 5 6 7 2 9 10 11 12


################
### KEYBOARD ###
################

# Keyboard - General
# --- Repeat rate increase
xset r rate 200 25

# When Colemak set, allow Caps-Lock as Backspace to repeat
# xset r 66


###################
### PERIPHERALS ###
###################

# Wacom
# --- Map pen & eraser to left monitor, & force proportions

# Pen 
xsetwacom set 12 MapToOutput HEAD-0
# Force proportions
xsetwacom set 12 Area 0 0 31496 17716
# Eraser
xsetwacom set 21 MapToOutput HEAD-0
